name: hue_dart
description: A library for creating Philips Hue apps in Flutter and/or AngularDart.
version: 0.1.1
homepage: https://github.com/Jairzinno/hue_dart
author: Jairzinno Henriquez <jairzinnohenriquez@gmail.com>

environment:
  sdk: '>=2.0.0-dev.69.0 <3.0.0'

dependencies:
 intl: "^0.15.6"
# json_serializable:
 http: "^0.11.3+16"
 built_collection: '>=2.0.0 <5.0.0'
 built_value: '>=5.5.5 <7.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator: ^6.1.6
  mockito: "^3.0.0"

#dependency_overrides:
#  analyzer: ^0.33.3